### ISSUE TITLE
[Bug] OpenCSV library has a limited CSV support we need to switch to Apache CSV

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [petrochenko-pavel-a/ds-ide#2]
[Bug] OpenCSV library has a limited CSV support we need to switch to Apache CSV

**Comment by petrochenko-pavel-a** [comment]
This also means that we should include Apache CSV into product

**Comment by 32kda** [comment]
Orbit build already has it: https://download.eclipse.org/tools/orbit/downloads/drops/R20190827152740/

Need to reuse given ver.
